name = "TensorRules"
uuid = "f4bef1b4-b92c-4d5f-a4ba-6d6989c7744d"
authors = ["Hayate Nakano <nakanodesu@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
MacroTools = "0.5"
ChainRulesCore = "0.9"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
